### ISSUE TITLE
JSON Importer/Exporter

### ISSUE THREAD

**Issue by oberstet** [crossbario/txaio-etcd#11]
We should include a basic etcd importer/exporter with this Python package. This is straight forward to implement given the library functionality, and it is highly useful (eg for CFC, we could need such a thing).

Eg the package should register two commands:

1. `etcd-export`
2. `etcd-import`

to dump the whole etcd database into a JSON file containing a single elements, a map with string keys from etcd, and arbitrary objects as value.

> Not 100% sure about command naming here. It could even be only 1 command. I don't care much.

The exporter by default assumes all keys in etcd being of type string (base64 encoded), and all values in etcd being serialized (utf8) JSON.

The keys in the generated JSON file for the top level map should be sorted ascending. And the JSON file should be pretty printed, for human consumption.

The importer reads such a JSON file and imports the data into etcd. The import operation should be conducted in a single etcd transaction, and the transaction should only touch exactly those keys that have changed, are new or are deleted now.

For command line parsing, the built in `argparse` module is fine (no new dependency).

**Comment by oberstet** [comment]
@om26er so this is a chance to write some lines of Python we could really make use of! this shouldn't be hard, so it's a nice start to get you familiar with more areas;) Will write more in a minute rgd yet another area ..

**Comment by om26er** [comment]
> @om26er so this is a chance to write some lines of Python we could really make use of! this shouldn't be hard, so it's a nice start to get you familiar with more areas;) Will write more in a minute rgd yet another area

Sounds good, I just started looking into this, will come up with something preliminary soonish.

**Comment by om26er** [comment]
@oberstet I have a very basic exporter in place, need to clear a few questions.

- Should it export `key` and `value` as human readable text or shall it be base64 encoded as grabbed from etcd ?
- Are `key` and `value` the only thing that we should export ?

A dump after decoding the `key` and `value` looks like this
```
[
    {
        "key": "/users/1",
        "value": "asdfg"
    },
    {
        "key": "location",
        "value": "germany"
    },
    {
        "key": "name",
        "value": "crossbar"
    },
    {
        "key": "type",
        "value": "company"
    }
]
```
an undecoded variant looks like
```
[
    {
        "key": "L3VzZXJzLzE=",
        "value": "YXNkZmc="
    },
    {
        "key": "bG9jYXRpb24=",
        "value": "Z2VybWFueQ=="
    },
    {
        "key": "bmFtZQ==",
        "value": "Y3Jvc3NiYXI="
    },
    {
        "key": "dHlwZQ==",
        "value": "Y29tcGFueQ=="
    }
]
```

Here is how the raw response looks like
```
om26er@chaotic:~$ http POST http://localhost:2379/v3alpha/kv/range key=AA== range_end=AA==
HTTP/1.1 200 OK
Content-Length: 534
Content-Type: application/json
Date: Mon, 07 Aug 2017 11:30:27 GMT

{
    "count": "4",
    "header": {
        "cluster_id": "9812235436358674032",
        "member_id": "18391291000126184887",
        "raft_term": "2",
        "revision": "15"
    },
    "kvs": [
        {
            "create_revision": "15",
            "key": "L3VzZXJzLzE=",
            "mod_revision": "15",
            "value": "YXNkZmc=",
            "version": "1"
        },
        {
            "create_revision": "14",
            "key": "bG9jYXRpb24=",
            "mod_revision": "14",
            "value": "Z2VybWFueQ==",
            "version": "1"
        },
        {
            "create_revision": "12",
            "key": "bmFtZQ==",
            "mod_revision": "12",
            "value": "Y3Jvc3NiYXI=",
            "version": "1"
        },
        {
            "create_revision": "13",
            "key": "dHlwZQ==",
            "mod_revision": "13",
            "value": "Y29tcGFueQ==",
            "version": "1"
        }
    ]
}
```

**Comment by oberstet** [comment]
> Should it export key and value as human readable text or shall it be base64 encoded as grabbed from etcd ?

It should print/export the human readable text (that is, the output _from_ base64 decoding

> Are key and value the only thing that we should export ?

Pretty much, yeah.

Rgd output format, we could simplify it:

```json
{
     "/users/1": "asdfg",
     "location": "germany",
     "foo": [1, 2, 3],
     "/bar/baz": {"foo": 23, "bar", [1, 2, 3]}
...
}
```
 or even a simple CSV:

```
"users/1", "asdfg"
"location", "germany"
"foo", [1, 2, 3]
"/bar/baz", {"foo": 23, "bar", [1, 2, 3]}
```

The last format is: first (decoded) key, the comma, then (single line) JSON (utf8), then CRLF.

This should allow us to directly import an exported dump eg into a PostgreSQL table with 2 columns: TEXT, JSONB

Maybe a `--output-format` switch would be cool ...

**Comment by oberstet** [comment]
@om26er cool! merged, and slightly adjusted the exporter code.

Here is exporting CFC database:

```console
(cpy361_13) oberstet@thinkpad-t430s:~/scm/crossbario/txaio-etcd$ etcd-export 
{
    "/com.crossbario.fabric/auth/node/7582a95a7aff6c8e7d4c6bd5e2a2308b5f637b65c1cc510056707adea678e9ea": {
        "authid": "cf1",
        "extra": null,
        "realm": "oberstet"
    },
    "/com.crossbario.fabric/auth/user/2074644d3ffab166b58ec72ebfcd5c8e8488ffc3dc325c6263870b351122d81c": {
        "activated": "2017-08-07T16:19:03.370Z",
        "activation-code": "RESF-MQPJ-WPYQ",
        "created": "2017-08-07T16:18:26.224Z",
        "email": "tobias.oberstein@gmail.com",
        "pubkey": "2074644d3ffab166b58ec72ebfcd5c8e8488ffc3dc325c6263870b351122d81c",
        "status": "active",
        "type": "registration"
    },
    "/com.crossbario.fabric/auth/user/tobias.oberstein@gmail.com/pubkey/2074644d3ffab166b58ec72ebfcd5c8e8488ffc3dc325c6263870b351122d81c": {
        "activated": "2017-08-07T16:19:03.370Z",
        "activation-code": "RESF-MQPJ-WPYQ",
        "created": "2017-08-07T16:18:26.224Z",
        "email": "tobias.oberstein@gmail.com",
        "pubkey": "2074644d3ffab166b58ec72ebfcd5c8e8488ffc3dc325c6263870b351122d81c",
        "status": "active",
        "type": "registration"
    },
    "/com.crossbario.fabric/auth/user/tobias.oberstein@gmail.com/realm/oberstet": {
        "roles": [
            "owner"
        ]
    },
    "/com.crossbario.fabric/realm/oberstet": {
        "cf_container_worker": "cfcontainer1",
        "cf_node": "cfnode1",
        "cf_router_worker": "cfrouter1",
        "created": "2017-08-07T16:41:17.829Z",
        "name": "oberstet",
        "owner": "tobias.oberstein@gmail.com"
    },
    "/com.crossbario.fabric/user/tobias.oberstein@gmail.com": {
        "email": "tobias.oberstein@gmail.com",
        "registered": "2017-08-07T16:19:03.370Z"
    }
}
```

**Comment by oberstet** [comment]
Note: The CFC database has keys being plain strings (utf8 encoded), and value all being serialized JSON (utf8 encoded).

Together with the importer (yet to be done), this will allow us to debug the CFC db code, and manually patch the CFC db (during development).

**Comment by om26er** [comment]
FYI, etc-export chickens out on master for me:
```
om26er@chaotic:~/code/crossbario/txaio-etcd$ etcd-export 
main function encountered error
Traceback (most recent call last):
  File "/home/om26er/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 500, in errback
    self._startRunCallbacks(fail)
  File "/home/om26er/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
  File "/home/om26er/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/om26er/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/home/om26er/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/om26er/.local/lib/python3.5/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.5/dist-packages/txaioetcd/cli/exporter.py", line 77, in export_as_json
    res = yield _get_all_keys(reactor, key_type, value_type, etcd_address)
  File "/home/om26er/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.5/dist-packages/txaioetcd/cli/exporter.py", line 64, in _get_all_keys
    value = json.loads(item.value.decode('utf8'))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by oberstet** [comment]
@om26er likely your etcd db hasn't JSON values? Just pushed another commit .. could you try: `etcd-export --value-type binary` ? Or even `etcd-export --key-type binary --value-type binary`. The latter must always work.

**Comment by om26er** [comment]
these two commands work, yes. Also all `values` in my etcd database are strings.

**Comment by oberstet** [comment]
Ok, then we probably should have 3 choices for both `--value-type` and `--key-type`: `choices=['utf8', 'json', 'binary']`.

> For CFC, we only need `--key-type utf8` and `--value-type json` though ..

**Comment by oberstet** [comment]
@om26er btw, do you have time for a 30min chat about areas of work? IRC?

**Comment by om26er** [comment]
> Ok, then we probably should have 3 choices for both --value-type and --key-type: choices=['utf8', 'json', 'binary'].

Done, also proposed etc-import https://github.com/crossbario/txaio-etcd/pull/13

**Comment by om26er** [comment]
Both importer and exporter landed and we already did a release with those features.
