### ISSUE TITLE
Implement treq alternative for asyncio

### ISSUE THREAD

**Issue by oberstet** [crossbario/txaio-etcd#2]

**Comment by meejah** [comment]
aiohttp has a client; not sure how it compares to treq.

https://aiohttp.readthedocs.io/en/stable/client.html#aiohttp-client

**Comment by om26er** [comment]
I have been using aiohttp for some experiments, seems to work fine for me. It seems to be in active development so I guess we can depend on it.

**Comment by oberstet** [comment]
Sounds good! Yeah, we can definitely rely on aiohttp, I know the author;)

**Comment by oberstet** [comment]
so this has landed via https://github.com/crossbario/txaio-etcd/pull/18
